package com.simas.vismajavadevelopertask.model;

public enum Category {
    ACTION_AND_ADVENTURE, CLASSIC, CRIME, DRAMA, FANTASY, POETRY, SCIENCE_FICTION,DOCUMENTARY, COMPUTING_INTERNET, PSYCHOLOGY, ROMANCE;
}
